listen_port: 8080
strategy: round_robin   # or least_cpu
monitor_interval_seconds: 5
targets:
  - name: app1
    host_port: 8081
  - name: app2
    host_port: 8082
  - name: app3
    host_port: 8083

